server:
  port: 8081
  servlet:
    context-path: /notification-api

spring:
  application:
    name: NOTIFICATION-SERVICE
  profiles:
    default: local

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka-host}:8761/eureka