version: '3.9'
services:
  config-server:
    image: config-server:1.0-snapshot
    ports:
      - 8888:8888
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health/readiness | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s

  eureka-server:
    image: eureka-server:1.0-snapshot
    ports:
      - 8761:8761
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
    depends_on:
      config-server:
        condition: service_healthy

  notification-api:
    image: notification-api:1.0-snapshot
    ports:
      - 8081:8081
    depends_on:
      eureka-server:
        condition: service_healthy

  payment-api:
    image: payment-api:1.0-snapshot
    ports:
      - 8082:8082
    healthcheck:
      test: "curl --fail --silent localhost:8082/payment-api/actuator/health/readiness | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
    depends_on:
      eureka-server:
        condition: service_healthy

  gateway:
    image: gateway:1.0-snapshot
    ports:
      - 9090:9090
    depends_on:
      payment-api:
        condition: service_healthy