server:
  port: 9090

spring:
  application:
    name: GATEWAY
  profiles:
    default: local
  cloud:
    gateway:
      routes:
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-api/**

        - id: NOTIFICATION-SERVICE
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification-api/**

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka-host}:8761/eureka
