eureka:
  instance:
    prefer-ip-address: yes
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server-0.eureka-svc:8761/eureka,http://eureka-server-1.eureka-svc:8761/eureka

spring:
  config:
    import: "configserver:http://config-server-svc:8888"